Repository CryptoptimaDevTeam/mvp, pull requests merged in 2023-06, with the labels that each got.

#58 chore - #57: CICD 위한 appspec.yml, deploy.sh 생성
  .github/workflows/deploy.yml
  front/appspec.yml
  front/deploy.sh
Labels: Chore, FE

#60 fix - #57: deploy.yml 일부 코드 재수정
  .github/workflows/deploy.yml
Labels: Fix, FE

#62 fix - #57: deploy.yml 일부 코드 마지막 수정
  .github/workflows/deploy.yml
Labels: Fix, FE

#64 remove - #22: 사용하지 않는 RegistartionLayout 파일 삭제
  front/layout/registrationLayout.tsx
Labels: Remove, FE

#65 fix: OAuth2 email, username 파라미터 수정
  server/src/main/java/CryptOptima/server/auth/oauth/handler/OAuth2UserSuccessHandler.java
Labels: Fix, BE
