Repository CryptoptimaDevTeam/mvp, pull requests merged in 2023-08, with the labels that each got.

#73 fix: ErrorResponder utility status 코드 수정
  server/src/main/java/CryptOptima/server/global/exception/GlobalExceptionAdvice.java
  server/src/main/java/CryptOptima/server/global/utils/ErrorResponder.java
  server/src/main/java/CryptOptima/server/security/handler/ManagerAuthenticationFailureHandler.java
Labels: Refactor, Fix, BE

#74 fix - #67: AccessToken 재발급, 로그아웃 수정
  server/build.gradle
  server/src/main/java/CryptOptima/server/security/configs/PasswordEncoderConfig.java
  server/src/main/java/CryptOptima/server/security/filter/JwtVerificationFilter.java
  server/src/main/java/CryptOptima/server/security/handler/ManagerAuthenticationSuccessHandler.java
Labels: Fix, Feat, BE

#76 feat - #67: refreshToken 검증, 토큰 만료 시간 제한 추가
  server/src/main/java/CryptOptima/server/security/jwt/JwtServiceImpl.java
  server/src/main/resources/application-server.yml
Labels: Feat, BE

#77 feat - #72: coin scheduling 구현
  server/src/main/java/CryptOptima/server/ServerApplication.java
  server/src/main/java/CryptOptima/server/global/schedule/ScheduledTasks.java
  server/src/main/java/CryptOptima/server/security/jwt/RefreshToken.java
Labels: Feat, BE

#80 fix: validation 라이브러리 import문 삭제
  server/src/main/java/CryptOptima/server/domain/manager/ManagerController.java
Labels: Fix, BE

#81 feat: redis property 등록
  server/src/main/resources/application-server.yml
Labels: Feat, BE

#82 feat: Front-end Landing Page 제작중
  front/components/blocks/card.tsx
  front/data/registrationStatic.tsx
  front/pages/index.tsx
  front/pages/main.tsx
  front/pages/pre-resister.tsx
  front/pages/registration/index.tsx
Labels: Feat, FE

#86 feat - #85: 설문조사 API 구현
  server/build.gradle
  server/src/main/java/CryptOptima/server/domain/survey/controller/SurveyController.java
  server/src/main/java/CryptOptima/server/domain/survey/dto/SurveyDto.java
  server/src/main/java/CryptOptima/server/domain/survey/dto/SurveyMapper.java
  server/src/main/java/CryptOptima/server/domain/survey/entity/Survey.java
  server/src/main/java/CryptOptima/server/domain/survey/repository/QSurveyRepository.java
  server/src/main/java/CryptOptima/server/domain/survey/repository/SurveyRepository.java
  server/src/main/java/CryptOptima/server/domain/survey/service/SurveyService.java
  server/src/main/java/CryptOptima/server/domain/survey/service/SurveyServiceImpl.java
  server/src/main/java/CryptOptima/server/global/exception/ExceptionCode.java
  server/src/main/java/CryptOptima/server/global/utils/IpUtils.java
  server/src/main/resources/application-server.yml
Labels: Feat, BE

#91 fix: landing page 에러 수정 및 deploy.sh 수정
  front/components/atoms/button.tsx
  front/deploy.sh
  front/module/preRegister.ts
  front/pages/pre-register/index.tsx
Labels: Fix, FE

#93 fix - #92: deploy.sh 수정
  front/deploy.sh
Labels: Fix, FE

#94 fix - #92: package.json 코드 수정
  front/package.json
Labels: Fix, FE

#95 fix - #92: package.json 수정
  front/package.json
Labels: Fix, FE

#96 fix - #92: appspec.yml 및 deploy.sh 수정
  front/appspec.yml
  front/deploy.sh
Labels: Fix, FE

#102 fix - #92: alert 관련 에러 수정-2
  front/components/atoms/alert.tsx
Labels: Fix, FE

#104 design - #103: Alert 반응형 디자인 구현 및 일부 디자인 수정
  front/components/atoms/alert.tsx
  front/pages/pre-register/index.tsx
Labels: Design, FE
